// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserDetails struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDetails) Reset()         { *m = UserDetails{} }
func (m *UserDetails) String() string { return proto.CompactTextString(m) }
func (*UserDetails) ProtoMessage()    {}
func (*UserDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *UserDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDetails.Unmarshal(m, b)
}
func (m *UserDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDetails.Marshal(b, m, deterministic)
}
func (m *UserDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDetails.Merge(m, src)
}
func (m *UserDetails) XXX_Size() int {
	return xxx_messageInfo_UserDetails.Size(m)
}
func (m *UserDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDetails.DiscardUnknown(m)
}

var xxx_messageInfo_UserDetails proto.InternalMessageInfo

func (m *UserDetails) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *UserDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Permission struct {
	Permission           string   `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
	For                  string   `protobuf:"bytes,2,opt,name=for,proto3" json:"for,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

func (m *Permission) GetFor() string {
	if m != nil {
		return m.For
	}
	return ""
}

type AuthenticateRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Audience             string   `protobuf:"bytes,3,opt,name=audience,proto3" json:"audience,omitempty"`
	Duration             uint32   `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthenticateRequest) GetAudience() string {
	if m != nil {
		return m.Audience
	}
	return ""
}

func (m *AuthenticateRequest) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type AuthenticateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Deprecated: Do not use.
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *AuthenticateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AuthenticateResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type InvalidateTokenResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidateTokenResponse) Reset()         { *m = InvalidateTokenResponse{} }
func (m *InvalidateTokenResponse) String() string { return proto.CompactTextString(m) }
func (*InvalidateTokenResponse) ProtoMessage()    {}
func (*InvalidateTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *InvalidateTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidateTokenResponse.Unmarshal(m, b)
}
func (m *InvalidateTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidateTokenResponse.Marshal(b, m, deterministic)
}
func (m *InvalidateTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidateTokenResponse.Merge(m, src)
}
func (m *InvalidateTokenResponse) XXX_Size() int {
	return xxx_messageInfo_InvalidateTokenResponse.Size(m)
}
func (m *InvalidateTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidateTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidateTokenResponse proto.InternalMessageInfo

func (m *InvalidateTokenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type TokenValidResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenValidResponse) Reset()         { *m = TokenValidResponse{} }
func (m *TokenValidResponse) String() string { return proto.CompactTextString(m) }
func (*TokenValidResponse) ProtoMessage()    {}
func (*TokenValidResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *TokenValidResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenValidResponse.Unmarshal(m, b)
}
func (m *TokenValidResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenValidResponse.Marshal(b, m, deterministic)
}
func (m *TokenValidResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenValidResponse.Merge(m, src)
}
func (m *TokenValidResponse) XXX_Size() int {
	return xxx_messageInfo_TokenValidResponse.Size(m)
}
func (m *TokenValidResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenValidResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenValidResponse proto.InternalMessageInfo

func (m *TokenValidResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type RegistrationRequest struct {
	EmailAddress         string   `protobuf:"bytes,1,opt,name=emailAddress,proto3" json:"emailAddress,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (m *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(m, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *RegistrationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegistrationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegistrationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationResponse) Reset()         { *m = RegistrationResponse{} }
func (m *RegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*RegistrationResponse) ProtoMessage()    {}
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *RegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationResponse.Unmarshal(m, b)
}
func (m *RegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationResponse.Marshal(b, m, deterministic)
}
func (m *RegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationResponse.Merge(m, src)
}
func (m *RegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_RegistrationResponse.Size(m)
}
func (m *RegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationResponse proto.InternalMessageInfo

func (m *RegistrationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*UserDetails)(nil), "UserDetails")
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*Permission)(nil), "Permission")
	proto.RegisterType((*AuthenticateRequest)(nil), "AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "AuthenticateResponse")
	proto.RegisterType((*InvalidateTokenResponse)(nil), "InvalidateTokenResponse")
	proto.RegisterType((*TokenValidResponse)(nil), "TokenValidResponse")
	proto.RegisterType((*RegistrationRequest)(nil), "RegistrationRequest")
	proto.RegisterType((*RegistrationResponse)(nil), "RegistrationResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x4b, 0x6b, 0xdb, 0x40,
	0x10, 0xc7, 0x91, 0x5f, 0x75, 0x47, 0x2e, 0x2d, 0x2b, 0x99, 0x0a, 0xe1, 0x16, 0xb3, 0x27, 0xd3,
	0x96, 0xc5, 0xd8, 0x87, 0x1e, 0x0a, 0x05, 0x97, 0x86, 0xe0, 0x5b, 0x50, 0x1e, 0xf7, 0x8d, 0x34,
	0x89, 0x97, 0xd8, 0x92, 0xb2, 0xbb, 0x72, 0x3e, 0x45, 0x4e, 0xf9, 0xc2, 0x61, 0xf5, 0xf2, 0x03,
	0x85, 0xe4, 0x90, 0xdb, 0xce, 0xcc, 0x7f, 0xff, 0x9a, 0xfd, 0xcd, 0x08, 0x80, 0x67, 0x7a, 0xc5,
	0x52, 0x99, 0xe8, 0x84, 0x9e, 0x80, 0x7d, 0xa9, 0x50, 0xfe, 0x47, 0xcd, 0xc5, 0x5a, 0x11, 0x0a,
	0x03, 0xdc, 0x70, 0xb1, 0x5e, 0x44, 0x91, 0x44, 0xa5, 0x3c, 0x6b, 0x6c, 0x4d, 0x3e, 0x06, 0x07,
	0x39, 0x42, 0xa0, 0x13, 0xf3, 0x0d, 0x7a, 0xad, 0xbc, 0x96, 0x9f, 0xe9, 0x37, 0xe8, 0x5e, 0x24,
	0x77, 0x18, 0x13, 0x17, 0xba, 0xda, 0x1c, 0xca, 0x9b, 0x45, 0x40, 0xff, 0x02, 0x9c, 0xa1, 0xdc,
	0x08, 0xa5, 0x44, 0x12, 0x93, 0xef, 0x00, 0x69, 0x1d, 0x95, 0xc2, 0xbd, 0x0c, 0xf9, 0x02, 0xed,
	0x9b, 0x44, 0x96, 0xfe, 0xe6, 0x48, 0x1f, 0x2d, 0x70, 0x16, 0x99, 0x5e, 0x61, 0xac, 0x45, 0xc8,
	0x35, 0x06, 0x78, 0x9f, 0xa1, 0xd2, 0x6f, 0x6a, 0xd7, 0x87, 0x7e, 0xca, 0x95, 0x7a, 0x48, 0x64,
	0x54, 0x5a, 0xd6, 0xb1, 0xa9, 0xf1, 0x2c, 0x12, 0x18, 0x87, 0xe8, 0xb5, 0x8b, 0x5a, 0x15, 0x9b,
	0x5a, 0x94, 0x49, 0xae, 0x4d, 0x8f, 0x9d, 0xb1, 0x35, 0xf9, 0x14, 0xd4, 0x31, 0x0d, 0xc0, 0x3d,
	0x6c, 0x47, 0xa5, 0x49, 0xac, 0x90, 0x8c, 0xe0, 0x83, 0xca, 0xc2, 0xb0, 0x6a, 0xa5, 0xff, 0xaf,
	0xe5, 0x59, 0x41, 0x95, 0x22, 0xa3, 0x8a, 0x8d, 0x69, 0xc3, 0x9e, 0xf5, 0x58, 0x8e, 0xac, 0x62,
	0x34, 0x87, 0xaf, 0xcb, 0x78, 0xcb, 0xd7, 0x22, 0xe2, 0x1a, 0x8b, 0x4a, 0x65, 0xeb, 0x1d, 0xd9,
	0xd6, 0x96, 0xf4, 0x07, 0x90, 0x5c, 0x7a, 0x65, 0xee, 0xd5, 0x7a, 0x17, 0xba, 0xb9, 0x51, 0xa9,
	0x2e, 0x02, 0x2a, 0xc0, 0x09, 0xf0, 0x56, 0x28, 0x5d, 0x3c, 0xe2, 0xbd, 0x18, 0x56, 0xeb, 0xd0,
	0xde, 0x5b, 0x87, 0x29, 0xb8, 0x87, 0x9f, 0x7a, 0xed, 0x21, 0xb3, 0xa7, 0x16, 0xd8, 0x06, 0xe9,
	0x39, 0xca, 0xad, 0x08, 0x91, 0xfc, 0x81, 0xc1, 0x3e, 0x61, 0xe2, 0xb2, 0x86, 0xf9, 0xfb, 0x43,
	0xd6, 0x38, 0x86, 0x5f, 0xe0, 0x9c, 0xa2, 0xce, 0xc1, 0xec, 0xd6, 0x4e, 0x91, 0x12, 0xb8, 0x6f,
	0xb3, 0x5d, 0x76, 0x6a, 0x91, 0x9f, 0x30, 0x58, 0xaa, 0x1d, 0xc5, 0x5a, 0xe6, 0xb0, 0x06, 0xb4,
	0x73, 0xf8, 0x7c, 0x34, 0xa5, 0x5a, 0xef, 0xb1, 0x97, 0xe6, 0xf7, 0x1b, 0xfa, 0x05, 0x0e, 0x94,
	0xc4, 0x65, 0x0d, 0x43, 0xf0, 0x87, 0xac, 0x89, 0xd7, 0x75, 0x2f, 0xff, 0x49, 0xe7, 0xcf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x5b, 0x13, 0x5a, 0xfa, 0xb2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	GetTokenPermissions(ctx context.Context, in *Token, opts ...grpc.CallOption) (AuthService_GetTokenPermissionsClient, error)
	IsTokenValid(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenValidResponse, error)
	InvalidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*InvalidateTokenResponse, error)
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/AuthService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetTokenPermissions(ctx context.Context, in *Token, opts ...grpc.CallOption) (AuthService_GetTokenPermissionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AuthService_serviceDesc.Streams[0], "/AuthService/GetTokenPermissions", opts...)
	if err != nil {
		return nil, err
	}
	x := &authServiceGetTokenPermissionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AuthService_GetTokenPermissionsClient interface {
	Recv() (*Permission, error)
	grpc.ClientStream
}

type authServiceGetTokenPermissionsClient struct {
	grpc.ClientStream
}

func (x *authServiceGetTokenPermissionsClient) Recv() (*Permission, error) {
	m := new(Permission)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *authServiceClient) IsTokenValid(ctx context.Context, in *Token, opts ...grpc.CallOption) (*TokenValidResponse, error) {
	out := new(TokenValidResponse)
	err := c.cc.Invoke(ctx, "/AuthService/IsTokenValid", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) InvalidateToken(ctx context.Context, in *Token, opts ...grpc.CallOption) (*InvalidateTokenResponse, error) {
	out := new(InvalidateTokenResponse)
	err := c.cc.Invoke(ctx, "/AuthService/InvalidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, "/AuthService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	GetTokenPermissions(*Token, AuthService_GetTokenPermissionsServer) error
	IsTokenValid(context.Context, *Token) (*TokenValidResponse, error)
	InvalidateToken(context.Context, *Token) (*InvalidateTokenResponse, error)
	Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAuthServiceServer) GetTokenPermissions(req *Token, srv AuthService_GetTokenPermissionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTokenPermissions not implemented")
}
func (*UnimplementedAuthServiceServer) IsTokenValid(ctx context.Context, req *Token) (*TokenValidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsTokenValid not implemented")
}
func (*UnimplementedAuthServiceServer) InvalidateToken(ctx context.Context, req *Token) (*InvalidateTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvalidateToken not implemented")
}
func (*UnimplementedAuthServiceServer) Register(ctx context.Context, req *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetTokenPermissions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Token)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuthServiceServer).GetTokenPermissions(m, &authServiceGetTokenPermissionsServer{stream})
}

type AuthService_GetTokenPermissionsServer interface {
	Send(*Permission) error
	grpc.ServerStream
}

type authServiceGetTokenPermissionsServer struct {
	grpc.ServerStream
}

func (x *authServiceGetTokenPermissionsServer) Send(m *Permission) error {
	return x.ServerStream.SendMsg(m)
}

func _AuthService_IsTokenValid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).IsTokenValid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/IsTokenValid",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).IsTokenValid(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_InvalidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).InvalidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/InvalidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).InvalidateToken(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AuthService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthService_Authenticate_Handler,
		},
		{
			MethodName: "IsTokenValid",
			Handler:    _AuthService_IsTokenValid_Handler,
		},
		{
			MethodName: "InvalidateToken",
			Handler:    _AuthService_InvalidateToken_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _AuthService_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTokenPermissions",
			Handler:       _AuthService_GetTokenPermissions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "auth.proto",
}
