// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sensors.proto

package sensors

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SensorInfo struct {
	Unit                 string   `protobuf:"bytes,1,opt,name=unit,proto3" json:"unit,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sensor               string   `protobuf:"bytes,3,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Measurementname      string   `protobuf:"bytes,4,opt,name=measurementname,proto3" json:"measurementname,omitempty"`
	Measurementunit      string   `protobuf:"bytes,5,opt,name=measurementunit,proto3" json:"measurementunit,omitempty"`
	Hidden               bool     `protobuf:"varint,6,opt,name=hidden,proto3" json:"hidden,omitempty"`
	Site                 string   `protobuf:"bytes,7,opt,name=site,proto3" json:"site,omitempty"`
	Latitude             float64  `protobuf:"fixed64,8,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,9,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorInfo) Reset()         { *m = SensorInfo{} }
func (m *SensorInfo) String() string { return proto.CompactTextString(m) }
func (*SensorInfo) ProtoMessage()    {}
func (*SensorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96d375cab19813b, []int{0}
}

func (m *SensorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorInfo.Unmarshal(m, b)
}
func (m *SensorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorInfo.Marshal(b, m, deterministic)
}
func (m *SensorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorInfo.Merge(m, src)
}
func (m *SensorInfo) XXX_Size() int {
	return xxx_messageInfo_SensorInfo.Size(m)
}
func (m *SensorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SensorInfo proto.InternalMessageInfo

func (m *SensorInfo) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *SensorInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SensorInfo) GetSensor() string {
	if m != nil {
		return m.Sensor
	}
	return ""
}

func (m *SensorInfo) GetMeasurementname() string {
	if m != nil {
		return m.Measurementname
	}
	return ""
}

func (m *SensorInfo) GetMeasurementunit() string {
	if m != nil {
		return m.Measurementunit
	}
	return ""
}

func (m *SensorInfo) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *SensorInfo) GetSite() string {
	if m != nil {
		return m.Site
	}
	return ""
}

func (m *SensorInfo) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *SensorInfo) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type SensorData struct {
	Sensor               string   `protobuf:"bytes,1,opt,name=sensor,proto3" json:"sensor,omitempty"`
	Reading              string   `protobuf:"bytes,2,opt,name=reading,proto3" json:"reading,omitempty"`
	Measurementname      string   `protobuf:"bytes,3,opt,name=measurementname,proto3" json:"measurementname,omitempty"`
	Measurementunit      string   `protobuf:"bytes,4,opt,name=measurementunit,proto3" json:"measurementunit,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Unit                 string   `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitName             string   `protobuf:"bytes,7,opt,name=unitName,proto3" json:"unitName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorData) Reset()         { *m = SensorData{} }
func (m *SensorData) String() string { return proto.CompactTextString(m) }
func (*SensorData) ProtoMessage()    {}
func (*SensorData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96d375cab19813b, []int{1}
}

func (m *SensorData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorData.Unmarshal(m, b)
}
func (m *SensorData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorData.Marshal(b, m, deterministic)
}
func (m *SensorData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorData.Merge(m, src)
}
func (m *SensorData) XXX_Size() int {
	return xxx_messageInfo_SensorData.Size(m)
}
func (m *SensorData) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorData.DiscardUnknown(m)
}

var xxx_messageInfo_SensorData proto.InternalMessageInfo

func (m *SensorData) GetSensor() string {
	if m != nil {
		return m.Sensor
	}
	return ""
}

func (m *SensorData) GetReading() string {
	if m != nil {
		return m.Reading
	}
	return ""
}

func (m *SensorData) GetMeasurementname() string {
	if m != nil {
		return m.Measurementname
	}
	return ""
}

func (m *SensorData) GetMeasurementunit() string {
	if m != nil {
		return m.Measurementunit
	}
	return ""
}

func (m *SensorData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *SensorData) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *SensorData) GetUnitName() string {
	if m != nil {
		return m.UnitName
	}
	return ""
}

type GetSensorsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IncludeHidden        bool     `protobuf:"varint,2,opt,name=includeHidden,proto3" json:"includeHidden,omitempty"`
	Site                 []string `protobuf:"bytes,3,rep,name=site,proto3" json:"site,omitempty"`
	Unit                 []string `protobuf:"bytes,4,rep,name=unit,proto3" json:"unit,omitempty"`
	Sensor               []string `protobuf:"bytes,5,rep,name=sensor,proto3" json:"sensor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSensorsRequest) Reset()         { *m = GetSensorsRequest{} }
func (m *GetSensorsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSensorsRequest) ProtoMessage()    {}
func (*GetSensorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96d375cab19813b, []int{2}
}

func (m *GetSensorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSensorsRequest.Unmarshal(m, b)
}
func (m *GetSensorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSensorsRequest.Marshal(b, m, deterministic)
}
func (m *GetSensorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSensorsRequest.Merge(m, src)
}
func (m *GetSensorsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSensorsRequest.Size(m)
}
func (m *GetSensorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSensorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSensorsRequest proto.InternalMessageInfo

func (m *GetSensorsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetSensorsRequest) GetIncludeHidden() bool {
	if m != nil {
		return m.IncludeHidden
	}
	return false
}

func (m *GetSensorsRequest) GetSite() []string {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *GetSensorsRequest) GetUnit() []string {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *GetSensorsRequest) GetSensor() []string {
	if m != nil {
		return m.Sensor
	}
	return nil
}

type GetSensorReadingsRequest struct {
	Unit                 []string `protobuf:"bytes,1,rep,name=unit,proto3" json:"unit,omitempty"`
	Sensor               []string `protobuf:"bytes,2,rep,name=sensor,proto3" json:"sensor,omitempty"`
	Since                int64    `protobuf:"varint,3,opt,name=since,proto3" json:"since,omitempty"`
	Site                 []string `protobuf:"bytes,4,rep,name=site,proto3" json:"site,omitempty"`
	IgnoreHidden         bool     `protobuf:"varint,5,opt,name=ignoreHidden,proto3" json:"ignoreHidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSensorReadingsRequest) Reset()         { *m = GetSensorReadingsRequest{} }
func (m *GetSensorReadingsRequest) String() string { return proto.CompactTextString(m) }
func (*GetSensorReadingsRequest) ProtoMessage()    {}
func (*GetSensorReadingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96d375cab19813b, []int{3}
}

func (m *GetSensorReadingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSensorReadingsRequest.Unmarshal(m, b)
}
func (m *GetSensorReadingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSensorReadingsRequest.Marshal(b, m, deterministic)
}
func (m *GetSensorReadingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSensorReadingsRequest.Merge(m, src)
}
func (m *GetSensorReadingsRequest) XXX_Size() int {
	return xxx_messageInfo_GetSensorReadingsRequest.Size(m)
}
func (m *GetSensorReadingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSensorReadingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSensorReadingsRequest proto.InternalMessageInfo

func (m *GetSensorReadingsRequest) GetUnit() []string {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *GetSensorReadingsRequest) GetSensor() []string {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *GetSensorReadingsRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func (m *GetSensorReadingsRequest) GetSite() []string {
	if m != nil {
		return m.Site
	}
	return nil
}

func (m *GetSensorReadingsRequest) GetIgnoreHidden() bool {
	if m != nil {
		return m.IgnoreHidden
	}
	return false
}

type Field struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Crop                 string        `protobuf:"bytes,2,opt,name=crop,proto3" json:"crop,omitempty"`
	Sensors              []*SensorInfo `protobuf:"bytes,3,rep,name=sensors,proto3" json:"sensors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96d375cab19813b, []int{4}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetCrop() string {
	if m != nil {
		return m.Crop
	}
	return ""
}

func (m *Field) GetSensors() []*SensorInfo {
	if m != nil {
		return m.Sensors
	}
	return nil
}

type GetFieldsRequest struct {
	Name                 []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFieldsRequest) Reset()         { *m = GetFieldsRequest{} }
func (m *GetFieldsRequest) String() string { return proto.CompactTextString(m) }
func (*GetFieldsRequest) ProtoMessage()    {}
func (*GetFieldsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b96d375cab19813b, []int{5}
}

func (m *GetFieldsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFieldsRequest.Unmarshal(m, b)
}
func (m *GetFieldsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFieldsRequest.Marshal(b, m, deterministic)
}
func (m *GetFieldsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFieldsRequest.Merge(m, src)
}
func (m *GetFieldsRequest) XXX_Size() int {
	return xxx_messageInfo_GetFieldsRequest.Size(m)
}
func (m *GetFieldsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFieldsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFieldsRequest proto.InternalMessageInfo

func (m *GetFieldsRequest) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

func init() {
	proto.RegisterType((*SensorInfo)(nil), "SensorInfo")
	proto.RegisterType((*SensorData)(nil), "SensorData")
	proto.RegisterType((*GetSensorsRequest)(nil), "GetSensorsRequest")
	proto.RegisterType((*GetSensorReadingsRequest)(nil), "GetSensorReadingsRequest")
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterType((*GetFieldsRequest)(nil), "GetFieldsRequest")
}

func init() { proto.RegisterFile("sensors.proto", fileDescriptor_b96d375cab19813b) }

var fileDescriptor_b96d375cab19813b = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0xc6, 0x8e, 0x13, 0x4f, 0x5a, 0xa0, 0x23, 0x54, 0x4c, 0xd4, 0x4a, 0x91, 0x05, 0xc8,
	0x27, 0x13, 0x95, 0x33, 0x27, 0x2a, 0x02, 0x12, 0xe2, 0xe0, 0x0a, 0xee, 0x26, 0x1e, 0xc2, 0x4a,
	0xf6, 0x3a, 0x78, 0xd7, 0xdc, 0xb9, 0x70, 0xe3, 0xc6, 0x07, 0xf2, 0x29, 0xc8, 0xbb, 0x5e, 0xdb,
	0x49, 0x8d, 0x54, 0xf5, 0x94, 0x9d, 0x37, 0xe3, 0x99, 0x37, 0xef, 0xed, 0x06, 0x4e, 0x25, 0x09,
	0x59, 0x56, 0x32, 0xde, 0x57, 0xa5, 0x2a, 0xc3, 0x5f, 0x13, 0x80, 0x1b, 0x8d, 0xbc, 0x17, 0x5f,
	0x4b, 0x44, 0x70, 0x6b, 0xc1, 0x55, 0xc0, 0x56, 0x2c, 0xf2, 0x13, 0x7d, 0x6e, 0x30, 0x91, 0x16,
	0x14, 0x4c, 0x0c, 0xd6, 0x9c, 0xf1, 0x1c, 0x3c, 0xd3, 0x27, 0x70, 0x34, 0xda, 0x46, 0x18, 0xc1,
	0xc3, 0x82, 0x52, 0x59, 0x57, 0x54, 0x90, 0x50, 0xfa, 0x33, 0x57, 0x17, 0x1c, 0xc3, 0x47, 0x95,
	0x7a, 0xe8, 0xf4, 0x56, 0xa5, 0x9e, 0x7f, 0x0e, 0xde, 0x37, 0x9e, 0x65, 0x24, 0x02, 0x6f, 0xc5,
	0xa2, 0x79, 0xd2, 0x46, 0x0d, 0x2f, 0xc9, 0x15, 0x05, 0x33, 0xc3, 0xab, 0x39, 0xe3, 0x12, 0xe6,
	0x79, 0xaa, 0xb8, 0xaa, 0x33, 0x0a, 0xe6, 0x2b, 0x16, 0xb1, 0xa4, 0x8b, 0xf1, 0x02, 0xfc, 0xbc,
	0x14, 0x3b, 0x93, 0xf4, 0x75, 0xb2, 0x07, 0xc2, 0xbf, 0xcc, 0x0a, 0x71, 0x9d, 0xaa, 0x74, 0xb0,
	0x20, 0x3b, 0x58, 0x30, 0x80, 0x59, 0x45, 0x69, 0xc6, 0xc5, 0xae, 0xd5, 0xc3, 0x86, 0x63, 0xab,
	0x3b, 0x77, 0x5e, 0xdd, 0x1d, 0x5f, 0xfd, 0x02, 0x7c, 0xc5, 0x0b, 0x92, 0x2a, 0x2d, 0xf6, 0x5a,
	0x1e, 0x27, 0xe9, 0x81, 0xce, 0x2c, 0x6f, 0x60, 0xd6, 0x12, 0xe6, 0xcd, 0xef, 0xc7, 0x66, 0xbc,
	0x11, 0xa6, 0x8b, 0xc3, 0xdf, 0x0c, 0xce, 0x36, 0xa4, 0xcc, 0x96, 0x32, 0xa1, 0xef, 0x35, 0xc9,
	0xde, 0x5e, 0x36, 0xb0, 0xf7, 0x19, 0x9c, 0x72, 0xb1, 0xcd, 0xeb, 0x8c, 0xde, 0x19, 0xe5, 0x27,
	0x5a, 0xf9, 0x43, 0xb0, 0x33, 0xc0, 0x59, 0x39, 0x9d, 0x01, 0x96, 0x93, 0x6b, 0x30, 0x6b, 0x60,
	0xab, 0xe5, 0x54, 0xa3, 0x6d, 0x14, 0xfe, 0x61, 0x10, 0x74, 0x7c, 0x12, 0x23, 0xe3, 0x90, 0x56,
	0x7b, 0x13, 0xc7, 0x1a, 0x4d, 0x86, 0x8d, 0xf0, 0x31, 0x4c, 0x25, 0x17, 0x5b, 0x23, 0xb8, 0x93,
	0x98, 0xa0, 0xa3, 0xe7, 0x0e, 0xe8, 0x85, 0x70, 0xc2, 0x77, 0xa2, 0xac, 0xec, 0x5e, 0x53, 0xbd,
	0xd7, 0x01, 0x16, 0x7e, 0x86, 0xe9, 0x5b, 0x4e, 0x79, 0x36, 0xaa, 0x0c, 0x82, 0xbb, 0xad, 0xca,
	0xbd, 0x7d, 0x0c, 0xcd, 0x19, 0x9f, 0xc3, 0xac, 0x7d, 0x54, 0x5a, 0x8a, 0xc5, 0xd5, 0x22, 0xee,
	0x9f, 0x54, 0x62, 0x73, 0xe1, 0x0b, 0x78, 0xb4, 0x21, 0xa5, 0x5b, 0x8f, 0x88, 0xef, 0xd8, 0x11,
	0x57, 0x3f, 0x1d, 0x78, 0xd0, 0x7a, 0x74, 0x43, 0xd5, 0x0f, 0xbe, 0x25, 0x7c, 0x09, 0xd0, 0x1b,
	0x87, 0x18, 0xdf, 0x72, 0x71, 0x39, 0x1c, 0xb9, 0x66, 0xf8, 0x7a, 0xe0, 0xb4, 0x55, 0x16, 0x9f,
	0xc6, 0xff, 0x53, 0xbb, 0xfb, 0xbc, 0xb9, 0xfb, 0x6b, 0x86, 0x6f, 0xe0, 0xc9, 0x86, 0xd4, 0x87,
	0x54, 0x91, 0xbc, 0x7f, 0x93, 0x08, 0x4e, 0x3e, 0xed, 0xb3, 0x54, 0x91, 0x41, 0x71, 0x48, 0xf1,
	0x80, 0x2f, 0x46, 0xe0, 0x77, 0xca, 0xe0, 0x59, 0x7c, 0xac, 0xd2, 0xd2, 0x8b, 0x75, 0xbc, 0x66,
	0x78, 0x09, 0x0b, 0xd3, 0xd3, 0x38, 0xd4, 0x26, 0x6c, 0x41, 0x33, 0xf2, 0x9a, 0x72, 0xba, 0xc3,
	0xc8, 0x4b, 0x58, 0x98, 0xca, 0xd1, 0x46, 0x5f, 0x3c, 0xfd, 0xef, 0xf8, 0xea, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x54, 0x5b, 0x30, 0x73, 0x2e, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SensorsServiceClient is the client API for SensorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SensorsServiceClient interface {
	GetSensors(ctx context.Context, in *GetSensorsRequest, opts ...grpc.CallOption) (SensorsService_GetSensorsClient, error)
	GetSensorReadings(ctx context.Context, in *GetSensorReadingsRequest, opts ...grpc.CallOption) (SensorsService_GetSensorReadingsClient, error)
	GetLatestSensorReadings(ctx context.Context, in *GetSensorReadingsRequest, opts ...grpc.CallOption) (SensorsService_GetLatestSensorReadingsClient, error)
	UpdateSensor(ctx context.Context, in *SensorInfo, opts ...grpc.CallOption) (*SensorInfo, error)
	GetFields(ctx context.Context, in *GetFieldsRequest, opts ...grpc.CallOption) (SensorsService_GetFieldsClient, error)
	UpdateField(ctx context.Context, in *Field, opts ...grpc.CallOption) (*Field, error)
	DeleteSensor(ctx context.Context, in *SensorInfo, opts ...grpc.CallOption) (*SensorInfo, error)
	DeleteField(ctx context.Context, in *Field, opts ...grpc.CallOption) (*Field, error)
}

type sensorsServiceClient struct {
	cc *grpc.ClientConn
}

func NewSensorsServiceClient(cc *grpc.ClientConn) SensorsServiceClient {
	return &sensorsServiceClient{cc}
}

func (c *sensorsServiceClient) GetSensors(ctx context.Context, in *GetSensorsRequest, opts ...grpc.CallOption) (SensorsService_GetSensorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SensorsService_serviceDesc.Streams[0], "/SensorsService/GetSensors", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorsServiceGetSensorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SensorsService_GetSensorsClient interface {
	Recv() (*SensorInfo, error)
	grpc.ClientStream
}

type sensorsServiceGetSensorsClient struct {
	grpc.ClientStream
}

func (x *sensorsServiceGetSensorsClient) Recv() (*SensorInfo, error) {
	m := new(SensorInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorsServiceClient) GetSensorReadings(ctx context.Context, in *GetSensorReadingsRequest, opts ...grpc.CallOption) (SensorsService_GetSensorReadingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SensorsService_serviceDesc.Streams[1], "/SensorsService/GetSensorReadings", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorsServiceGetSensorReadingsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SensorsService_GetSensorReadingsClient interface {
	Recv() (*SensorData, error)
	grpc.ClientStream
}

type sensorsServiceGetSensorReadingsClient struct {
	grpc.ClientStream
}

func (x *sensorsServiceGetSensorReadingsClient) Recv() (*SensorData, error) {
	m := new(SensorData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorsServiceClient) GetLatestSensorReadings(ctx context.Context, in *GetSensorReadingsRequest, opts ...grpc.CallOption) (SensorsService_GetLatestSensorReadingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SensorsService_serviceDesc.Streams[2], "/SensorsService/GetLatestSensorReadings", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorsServiceGetLatestSensorReadingsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SensorsService_GetLatestSensorReadingsClient interface {
	Recv() (*SensorData, error)
	grpc.ClientStream
}

type sensorsServiceGetLatestSensorReadingsClient struct {
	grpc.ClientStream
}

func (x *sensorsServiceGetLatestSensorReadingsClient) Recv() (*SensorData, error) {
	m := new(SensorData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorsServiceClient) UpdateSensor(ctx context.Context, in *SensorInfo, opts ...grpc.CallOption) (*SensorInfo, error) {
	out := new(SensorInfo)
	err := c.cc.Invoke(ctx, "/SensorsService/UpdateSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorsServiceClient) GetFields(ctx context.Context, in *GetFieldsRequest, opts ...grpc.CallOption) (SensorsService_GetFieldsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SensorsService_serviceDesc.Streams[3], "/SensorsService/GetFields", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorsServiceGetFieldsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SensorsService_GetFieldsClient interface {
	Recv() (*Field, error)
	grpc.ClientStream
}

type sensorsServiceGetFieldsClient struct {
	grpc.ClientStream
}

func (x *sensorsServiceGetFieldsClient) Recv() (*Field, error) {
	m := new(Field)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sensorsServiceClient) UpdateField(ctx context.Context, in *Field, opts ...grpc.CallOption) (*Field, error) {
	out := new(Field)
	err := c.cc.Invoke(ctx, "/SensorsService/UpdateField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorsServiceClient) DeleteSensor(ctx context.Context, in *SensorInfo, opts ...grpc.CallOption) (*SensorInfo, error) {
	out := new(SensorInfo)
	err := c.cc.Invoke(ctx, "/SensorsService/DeleteSensor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorsServiceClient) DeleteField(ctx context.Context, in *Field, opts ...grpc.CallOption) (*Field, error) {
	out := new(Field)
	err := c.cc.Invoke(ctx, "/SensorsService/DeleteField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorsServiceServer is the server API for SensorsService service.
type SensorsServiceServer interface {
	GetSensors(*GetSensorsRequest, SensorsService_GetSensorsServer) error
	GetSensorReadings(*GetSensorReadingsRequest, SensorsService_GetSensorReadingsServer) error
	GetLatestSensorReadings(*GetSensorReadingsRequest, SensorsService_GetLatestSensorReadingsServer) error
	UpdateSensor(context.Context, *SensorInfo) (*SensorInfo, error)
	GetFields(*GetFieldsRequest, SensorsService_GetFieldsServer) error
	UpdateField(context.Context, *Field) (*Field, error)
	DeleteSensor(context.Context, *SensorInfo) (*SensorInfo, error)
	DeleteField(context.Context, *Field) (*Field, error)
}

// UnimplementedSensorsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSensorsServiceServer struct {
}

func (*UnimplementedSensorsServiceServer) GetSensors(req *GetSensorsRequest, srv SensorsService_GetSensorsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSensors not implemented")
}
func (*UnimplementedSensorsServiceServer) GetSensorReadings(req *GetSensorReadingsRequest, srv SensorsService_GetSensorReadingsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSensorReadings not implemented")
}
func (*UnimplementedSensorsServiceServer) GetLatestSensorReadings(req *GetSensorReadingsRequest, srv SensorsService_GetLatestSensorReadingsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLatestSensorReadings not implemented")
}
func (*UnimplementedSensorsServiceServer) UpdateSensor(ctx context.Context, req *SensorInfo) (*SensorInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSensor not implemented")
}
func (*UnimplementedSensorsServiceServer) GetFields(req *GetFieldsRequest, srv SensorsService_GetFieldsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFields not implemented")
}
func (*UnimplementedSensorsServiceServer) UpdateField(ctx context.Context, req *Field) (*Field, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateField not implemented")
}
func (*UnimplementedSensorsServiceServer) DeleteSensor(ctx context.Context, req *SensorInfo) (*SensorInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSensor not implemented")
}
func (*UnimplementedSensorsServiceServer) DeleteField(ctx context.Context, req *Field) (*Field, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteField not implemented")
}

func RegisterSensorsServiceServer(s *grpc.Server, srv SensorsServiceServer) {
	s.RegisterService(&_SensorsService_serviceDesc, srv)
}

func _SensorsService_GetSensors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSensorsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorsServiceServer).GetSensors(m, &sensorsServiceGetSensorsServer{stream})
}

type SensorsService_GetSensorsServer interface {
	Send(*SensorInfo) error
	grpc.ServerStream
}

type sensorsServiceGetSensorsServer struct {
	grpc.ServerStream
}

func (x *sensorsServiceGetSensorsServer) Send(m *SensorInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _SensorsService_GetSensorReadings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSensorReadingsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorsServiceServer).GetSensorReadings(m, &sensorsServiceGetSensorReadingsServer{stream})
}

type SensorsService_GetSensorReadingsServer interface {
	Send(*SensorData) error
	grpc.ServerStream
}

type sensorsServiceGetSensorReadingsServer struct {
	grpc.ServerStream
}

func (x *sensorsServiceGetSensorReadingsServer) Send(m *SensorData) error {
	return x.ServerStream.SendMsg(m)
}

func _SensorsService_GetLatestSensorReadings_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSensorReadingsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorsServiceServer).GetLatestSensorReadings(m, &sensorsServiceGetLatestSensorReadingsServer{stream})
}

type SensorsService_GetLatestSensorReadingsServer interface {
	Send(*SensorData) error
	grpc.ServerStream
}

type sensorsServiceGetLatestSensorReadingsServer struct {
	grpc.ServerStream
}

func (x *sensorsServiceGetLatestSensorReadingsServer) Send(m *SensorData) error {
	return x.ServerStream.SendMsg(m)
}

func _SensorsService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorsServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorsService/UpdateSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorsServiceServer).UpdateSensor(ctx, req.(*SensorInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorsService_GetFields_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetFieldsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorsServiceServer).GetFields(m, &sensorsServiceGetFieldsServer{stream})
}

type SensorsService_GetFieldsServer interface {
	Send(*Field) error
	grpc.ServerStream
}

type sensorsServiceGetFieldsServer struct {
	grpc.ServerStream
}

func (x *sensorsServiceGetFieldsServer) Send(m *Field) error {
	return x.ServerStream.SendMsg(m)
}

func _SensorsService_UpdateField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Field)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorsServiceServer).UpdateField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorsService/UpdateField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorsServiceServer).UpdateField(ctx, req.(*Field))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorsService_DeleteSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorsServiceServer).DeleteSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorsService/DeleteSensor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorsServiceServer).DeleteSensor(ctx, req.(*SensorInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorsService_DeleteField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Field)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorsServiceServer).DeleteField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SensorsService/DeleteField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorsServiceServer).DeleteField(ctx, req.(*Field))
	}
	return interceptor(ctx, in, info, handler)
}

var _SensorsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SensorsService",
	HandlerType: (*SensorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateSensor",
			Handler:    _SensorsService_UpdateSensor_Handler,
		},
		{
			MethodName: "UpdateField",
			Handler:    _SensorsService_UpdateField_Handler,
		},
		{
			MethodName: "DeleteSensor",
			Handler:    _SensorsService_DeleteSensor_Handler,
		},
		{
			MethodName: "DeleteField",
			Handler:    _SensorsService_DeleteField_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSensors",
			Handler:       _SensorsService_GetSensors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSensorReadings",
			Handler:       _SensorsService_GetSensorReadings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetLatestSensorReadings",
			Handler:       _SensorsService_GetLatestSensorReadings_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFields",
			Handler:       _SensorsService_GetFields_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sensors.proto",
}
