dashboard = ["base.html", "navpage.html", "graphutil.html", "dashboard.html"]
sensor = ["base.html", "navpage.html", "graphutil.html", "sensor.html"]
sensor_list = ["base.html", "navpage.html", "sensor_list.html"]
sensor_add =  ["base.html", "navpage.html", "sensor_add.html"]
field_list = ["base.html", "navpage.html", "field_list.html"]
field = ["base.html", "navpage.html", "field.html"]
script_add = ["base.html", "navpage.html", "script_add.html"]
script_list = ["base.html", "navpage.html", "script_list.html"]
script_edit = ["base.html", "navpage.html", "script_edit.html"]
script_errors = ["base.html", "navpage.html", "script_errors.html"]