dashboard = ["base.html", "navpage.html", "graphutil.html", "dashboard.html"]
sensor = ["base.html", "navpage.html", "graphutil.html", "sensor.html"]
sensor_list = ["base.html", "navpage.html", "sensor_list.html"]
sensor_add =  ["base.html", "navpage.html", "sensor_add.html"]